MODEL:
  TYPE: cluster
  NAME: cluster_patch1_cifar_equal_shift2_multi
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 8 ]
    NUM_HEADS: [ 3, 6, 12 ]
    PATCH_SIZE: 1
  CLUSTER:
    POS_DIM: 2
    K: [64,16,4]
    CLUSTER_SIZE: 16
    POS_LAMBDA: [2.0,1.0,0.5]
    EQUAL_SIZE: True
    SHIFT: True
DATA:
  DATASET: cifar
  IMG_SIZE: 32
  BATCH_SIZE: 256
TRAIN:
  EPOCHS: 1000
