MODEL:
  TYPE: cluster
  NAME: cluster_patch1_cifar_cm
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 8 ]
    NUM_HEADS: [ 3, 6, 12 ]
    PATCH_SIZE: 1
  CLUSTER:
    POS_DIM: 2
    K: [0,0,0]
    CLUSTER_SIZE: 16
    MAX_CLUSTER_SIZE: 0
    POS_LAMBDA: [100.0,30.0,10.0]
DATA:
  DATASET: cifar
  IMG_SIZE: 32
  BATCH_SIZE: 1024
TRAIN:
  EPOCHS: 1000
