MODEL:
  TYPE: swin
  NAME: swin_tiny_patch1_window2_cifar_tmp2
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 8 ]
    NUM_HEADS: [ 3, 6, 12 ]
    WINDOW_SIZE: 2
    PATCH_SIZE: 1
DATA:
  DATASET: cifar
  IMG_SIZE: 32
  BATCH_SIZE: 256
TRAIN:
  EPOCHS: 1000
