MODEL:
  TYPE: swin
  NAME: swin_tiny_patch2_window4_cifar 
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 4
    PATCH_SIZE: 2
DATA:
  DATASET: cifar
  IMG_SIZE: 32
